version: 3

models:
  - name: int_energy_weather_hourly
    description: "Intermediate model for energy prices and weather categories"
    columns:
      - name: country_code
        tests:
          - not_null
          - accepted_values:
              values: ['EE', 'FI', 'LV', 'LT']

      - name: timestamp_utc
        tests:
          - not_null

      - name: temperature_category  
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Freezing', 'Cold', 'Mild', 'Warm']

      - name: wind_category      
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Low Wind', 'Medium Wind', 'High Wind']

      - name: solar_category
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Very Sunny', 'Sunny', 'Cloudy/Night']

      - name: cloud_category
        tests:
          - not_null
          - accepted_values:
              values: ['N/A', 'Clear Sky', 'Partly Cloudy', 'Overcast']