version: 4

models:
  - name: int_energy_weather_hourly
    description: "Intermediate model tested with native dbt tests only."
    columns:
      - name: country_code
        tests:
          - not_null
          - accepted_values:
              values: ['EE', 'FI', 'LV', 'LT']

      - name: timestamp_utc
        tests:
          - not_null

      - name: hour_utc
        tests:
          - not_null

      - name: price_eur_mwh
        tests:
          - not_null

      - name: temperature_2m_c
        tests:
          - not_null

      - name: wind_speed_10m_kmh
        tests:
          - not_null

      - name: shortwave_radiation
        tests:
          - not_null

      - name: cloud_cover
        tests:
          - not_null
